name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt update && sudo apt install -y cmake gcc make cppcheck clang-format

      - name: Lint (cppcheck)
        run: cppcheck --enable=all --inconclusive --quiet --error-exitcode=1 src include

      - name: Lint (clang-format)
        run: |
          find src include -name '*.c' -o -name '*.h' | xargs clang-format -n --Werror

      - name: Configure
        run: cmake -S . -B build -DENABLE_TESTING=ON

      - name: Build
        run: cmake --build build

      - name: Run demos
        run: |
          ./build/demo/lcd_demo_mock_effects
          ./build/demo/lcd_demo_mock_format
          ./build/demo/lcd_demo_xilinx

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --verbose
          ctest --output-junit test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results.xml
