name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake .. -DUSE_SIMULATION=ON

      - name: Build project
        run: |
          cd build
          make

      - name: List build contents
        run: ls -l build/

      - name: Run unit tests
        run: ./build/lcd_test
