name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install tools
        run: sudo apt update && sudo apt install -y cmake gcc python3

      # Build with all supported HALs
      - name: Build with Mock HAL
        run: python build_and_deploy.py mock

      - name: Build with Sim HAL
        run: python build_and_deploy.py sim

      - name: Build with Xilinx HAL
        run: python build_and_deploy.py xilinx

      # Package artifacts
      - name: Create release packages
        run: |
          # First, see what files actually exist
          echo "Available files in build/demo:"
          find build/demo -type f -ls
          
          # Create directories in case they don't exist
          mkdir -p release_packages
          
          # More robust approach with find
          find build/demo -name "*mock*" -type f -exec zip -j "release_packages/hd44780-mock-v${GITHUB_REF#refs/tags/v}.zip" {} \;
          find build/demo -name "*sim*" -type f -exec zip -j "release_packages/hd44780-sim-v${GITHUB_REF#refs/tags/v}.zip" {} \;
          find build/demo -name "*xilinx*" -type f -exec zip -j "release_packages/hd44780-xilinx-v${GITHUB_REF#refs/tags/v}.zip" {} \;
          
          # List created packages
          echo "Created packages:"
          ls -la release_packages/

      # Upload to GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release_packages/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
